project_name: volume-aws-ebs-csi-migration
release:
  github:
    owner: czomo
    name: volume-aws-ebs-csi-migration
builds:
  - id: volume-aws-ebs-csi-migration
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/czomo/volume-aws-ebs-csi-migration/pkg/version.version=
archives:
  - id: volume-aws-ebs-csi-migration
    builds:
    - volume-aws-ebs-csi-migration
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
