apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: volume-aws-ebs-csi-migration
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/czomo/volume-aws-ebs-csi-migration/releases/download/v0.1.0/volume-aws-ebs-csi-migration_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./volume-aws-ebs-csi-migration"
      to: "."
    - from: LICENSE
      to: "."
    bin: "volume-aws-ebs-csi-migration"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/czomo/volume-aws-ebs-csi-migration/releases/download/v0.1.0/volume-aws-ebs-csi-migration_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./volume-aws-ebs-csi-migration"
      to: "."
    - from: LICENSE
      to: "."
    bin: "volume-aws-ebs-csi-migration"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/czomo/volume-aws-ebs-csi-migration/releases/download/v0.1.0/volume-aws-ebs-csi-migration_windows_amd64.zip
    sha256: ""
    files:
    - from: "/volume-aws-ebs-csi-migration.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "volume-aws-ebs-csi-migration.exe"
  shortDescription: A new plugin
  homepage: https://github.com/czomo/volume-aws-ebs-csi-migration
  caveats: |
    Usage:
      $ kubectl volume-aws-ebs-csi-migration

    For additional options:
      $ kubectl volume-aws-ebs-csi-migration --help
      or https://github.com/czomo/volume-aws-ebs-csi-migration/blob/v0.1.0/doc/USAGE.md

  description: |
    This is plugin that helps you change provisioner of aws ebs driver to csi
